load("@rules_acx_tools//:def.bzl", "vector_test", "vector_validate_test")

vector_test(
  name = "example_test",
  srcs = ["config.toml"],
)

vector_validate_test(
  name = "validation_test",
  srcs = ["complete-example.toml"],
)
