load("@io_bazel_stardoc//stardoc:stardoc.bzl", "stardoc")

stardoc(
    name = "prometheus_docs",
    out = "prometheus_rules.md",
    input = "prometheus.bzl",
)

stardoc(
    name = "opa_docs",
    out = "opa_rules.md",
    input = "opa.bzl",
)

stardoc(
    name = "nomad_docs",
    out = "nomad_rules.md",
    input = "nomad.bzl",
)
